with-expecter: true
packages:
  github.com/amirdaaee/TGMon/internal/db:
    config:
      all: true
      dir: mocks/{{ .PackageName }}
  github.com/amirdaaee/TGMon/internal/bot:
    config:
      all: true
      dir: mocks/{{ .PackageName }}
