// Code generated by mockery v2.44.1. DO NOT EDIT.

package db

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIMinioClient is an autogenerated mock type for the IMinioClient type
type MockIMinioClient struct {
	mock.Mock
}

type MockIMinioClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMinioClient) EXPECT() *MockIMinioClient_Expecter {
	return &MockIMinioClient_Expecter{mock: &_m.Mock}
}

// CreateBucket provides a mock function with given fields: ctx
func (_m *MockIMinioClient) CreateBucket(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateBucket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMinioClient_CreateBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBucket'
type MockIMinioClient_CreateBucket_Call struct {
	*mock.Call
}

// CreateBucket is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIMinioClient_Expecter) CreateBucket(ctx interface{}) *MockIMinioClient_CreateBucket_Call {
	return &MockIMinioClient_CreateBucket_Call{Call: _e.mock.On("CreateBucket", ctx)}
}

func (_c *MockIMinioClient_CreateBucket_Call) Run(run func(ctx context.Context)) *MockIMinioClient_CreateBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIMinioClient_CreateBucket_Call) Return(_a0 error) *MockIMinioClient_CreateBucket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMinioClient_CreateBucket_Call) RunAndReturn(run func(context.Context) error) *MockIMinioClient_CreateBucket_Call {
	_c.Call.Return(run)
	return _c
}

// FileAdd provides a mock function with given fields: fileName, data, ctx
func (_m *MockIMinioClient) FileAdd(fileName string, data []byte, ctx context.Context) error {
	ret := _m.Called(fileName, data, ctx)

	if len(ret) == 0 {
		panic("no return value specified for FileAdd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, context.Context) error); ok {
		r0 = rf(fileName, data, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMinioClient_FileAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileAdd'
type MockIMinioClient_FileAdd_Call struct {
	*mock.Call
}

// FileAdd is a helper method to define mock.On call
//   - fileName string
//   - data []byte
//   - ctx context.Context
func (_e *MockIMinioClient_Expecter) FileAdd(fileName interface{}, data interface{}, ctx interface{}) *MockIMinioClient_FileAdd_Call {
	return &MockIMinioClient_FileAdd_Call{Call: _e.mock.On("FileAdd", fileName, data, ctx)}
}

func (_c *MockIMinioClient_FileAdd_Call) Run(run func(fileName string, data []byte, ctx context.Context)) *MockIMinioClient_FileAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(context.Context))
	})
	return _c
}

func (_c *MockIMinioClient_FileAdd_Call) Return(_a0 error) *MockIMinioClient_FileAdd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMinioClient_FileAdd_Call) RunAndReturn(run func(string, []byte, context.Context) error) *MockIMinioClient_FileAdd_Call {
	_c.Call.Return(run)
	return _c
}

// FileAddStr provides a mock function with given fields: fileName, data, ctx
func (_m *MockIMinioClient) FileAddStr(fileName string, data string, ctx context.Context) error {
	ret := _m.Called(fileName, data, ctx)

	if len(ret) == 0 {
		panic("no return value specified for FileAddStr")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, context.Context) error); ok {
		r0 = rf(fileName, data, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMinioClient_FileAddStr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileAddStr'
type MockIMinioClient_FileAddStr_Call struct {
	*mock.Call
}

// FileAddStr is a helper method to define mock.On call
//   - fileName string
//   - data string
//   - ctx context.Context
func (_e *MockIMinioClient_Expecter) FileAddStr(fileName interface{}, data interface{}, ctx interface{}) *MockIMinioClient_FileAddStr_Call {
	return &MockIMinioClient_FileAddStr_Call{Call: _e.mock.On("FileAddStr", fileName, data, ctx)}
}

func (_c *MockIMinioClient_FileAddStr_Call) Run(run func(fileName string, data string, ctx context.Context)) *MockIMinioClient_FileAddStr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(context.Context))
	})
	return _c
}

func (_c *MockIMinioClient_FileAddStr_Call) Return(_a0 error) *MockIMinioClient_FileAddStr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMinioClient_FileAddStr_Call) RunAndReturn(run func(string, string, context.Context) error) *MockIMinioClient_FileAddStr_Call {
	_c.Call.Return(run)
	return _c
}

// FileRm provides a mock function with given fields: fileName, ctx
func (_m *MockIMinioClient) FileRm(fileName string, ctx context.Context) error {
	ret := _m.Called(fileName, ctx)

	if len(ret) == 0 {
		panic("no return value specified for FileRm")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, context.Context) error); ok {
		r0 = rf(fileName, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMinioClient_FileRm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileRm'
type MockIMinioClient_FileRm_Call struct {
	*mock.Call
}

// FileRm is a helper method to define mock.On call
//   - fileName string
//   - ctx context.Context
func (_e *MockIMinioClient_Expecter) FileRm(fileName interface{}, ctx interface{}) *MockIMinioClient_FileRm_Call {
	return &MockIMinioClient_FileRm_Call{Call: _e.mock.On("FileRm", fileName, ctx)}
}

func (_c *MockIMinioClient_FileRm_Call) Run(run func(fileName string, ctx context.Context)) *MockIMinioClient_FileRm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(context.Context))
	})
	return _c
}

func (_c *MockIMinioClient_FileRm_Call) Return(_a0 error) *MockIMinioClient_FileRm_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMinioClient_FileRm_Call) RunAndReturn(run func(string, context.Context) error) *MockIMinioClient_FileRm_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMinioClient creates a new instance of MockIMinioClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMinioClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMinioClient {
	mock := &MockIMinioClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
