// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/minio/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/minio/client.go -destination=mocks/repository/minio/client.go -package=mocks_repository_minio
//

// Package mocks_repository_minio is a generated GoMock package.
package mocks_repository_minio

import (
	context "context"
	io "io"
	reflect "reflect"

	minio "github.com/minio/minio-go/v7"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectAPI is a mock of ObjectAPI interface.
type MockObjectAPI struct {
	ctrl     *gomock.Controller
	recorder *MockObjectAPIMockRecorder
	isgomock struct{}
}

// MockObjectAPIMockRecorder is the mock recorder for MockObjectAPI.
type MockObjectAPIMockRecorder struct {
	mock *MockObjectAPI
}

// NewMockObjectAPI creates a new mock instance.
func NewMockObjectAPI(ctrl *gomock.Controller) *MockObjectAPI {
	mock := &MockObjectAPI{ctrl: ctrl}
	mock.recorder = &MockObjectAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectAPI) EXPECT() *MockObjectAPIMockRecorder {
	return m.recorder
}

// BucketExists mocks base method.
func (m *MockObjectAPI) BucketExists(ctx context.Context, bucketName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BucketExists", ctx, bucketName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BucketExists indicates an expected call of BucketExists.
func (mr *MockObjectAPIMockRecorder) BucketExists(ctx, bucketName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BucketExists", reflect.TypeOf((*MockObjectAPI)(nil).BucketExists), ctx, bucketName)
}

// GetObject mocks base method.
func (m *MockObjectAPI) GetObject(ctx context.Context, bucketName, objectName string, opts minio.GetObjectOptions) (*minio.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, bucketName, objectName, opts)
	ret0, _ := ret[0].(*minio.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectAPIMockRecorder) GetObject(ctx, bucketName, objectName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockObjectAPI)(nil).GetObject), ctx, bucketName, objectName, opts)
}

// MakeBucket mocks base method.
func (m *MockObjectAPI) MakeBucket(ctx context.Context, bucketName string, opts minio.MakeBucketOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeBucket", ctx, bucketName, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeBucket indicates an expected call of MakeBucket.
func (mr *MockObjectAPIMockRecorder) MakeBucket(ctx, bucketName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeBucket", reflect.TypeOf((*MockObjectAPI)(nil).MakeBucket), ctx, bucketName, opts)
}

// PutObject mocks base method.
func (m *MockObjectAPI) PutObject(ctx context.Context, bucketName, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) (minio.UploadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, bucketName, objectName, reader, objectSize, opts)
	ret0, _ := ret[0].(minio.UploadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectAPIMockRecorder) PutObject(ctx, bucketName, objectName, reader, objectSize, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockObjectAPI)(nil).PutObject), ctx, bucketName, objectName, reader, objectSize, opts)
}

// RemoveObject mocks base method.
func (m *MockObjectAPI) RemoveObject(ctx context.Context, bucketName, objectName string, opts minio.RemoveObjectOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveObject", ctx, bucketName, objectName, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveObject indicates an expected call of RemoveObject.
func (mr *MockObjectAPIMockRecorder) RemoveObject(ctx, bucketName, objectName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveObject", reflect.TypeOf((*MockObjectAPI)(nil).RemoveObject), ctx, bucketName, objectName, opts)
}

// StatObject mocks base method.
func (m *MockObjectAPI) StatObject(ctx context.Context, bucketName, objectName string, opts minio.StatObjectOptions) (minio.ObjectInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatObject", ctx, bucketName, objectName, opts)
	ret0, _ := ret[0].(minio.ObjectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatObject indicates an expected call of StatObject.
func (mr *MockObjectAPIMockRecorder) StatObject(ctx, bucketName, objectName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatObject", reflect.TypeOf((*MockObjectAPI)(nil).StatObject), ctx, bucketName, objectName, opts)
}
