// Code generated by MockGen. DO NOT EDIT.
// Source: container.go
//
// Generated by this command:
//
//	mockgen -source=container.go -destination=../../mocks/stream/container.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	stream "github.com/amirdaaee/TGMon/internal/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockIWorkerContainer is a mock of IWorkerContainer interface.
type MockIWorkerContainer struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkerContainerMockRecorder
	isgomock struct{}
}

// MockIWorkerContainerMockRecorder is the mock recorder for MockIWorkerContainer.
type MockIWorkerContainerMockRecorder struct {
	mock *MockIWorkerContainer
}

// NewMockIWorkerContainer creates a new mock instance.
func NewMockIWorkerContainer(ctrl *gomock.Controller) *MockIWorkerContainer {
	mock := &MockIWorkerContainer{ctrl: ctrl}
	mock.recorder = &MockIWorkerContainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkerContainer) EXPECT() *MockIWorkerContainerMockRecorder {
	return m.recorder
}

// GetNextWorker mocks base method.
func (m *MockIWorkerContainer) GetNextWorker() stream.IWorker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextWorker")
	ret0, _ := ret[0].(stream.IWorker)
	return ret0
}

// GetNextWorker indicates an expected call of GetNextWorker.
func (mr *MockIWorkerContainerMockRecorder) GetNextWorker() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextWorker", reflect.TypeOf((*MockIWorkerContainer)(nil).GetNextWorker))
}

// GetWorkerPool mocks base method.
func (m *MockIWorkerContainer) GetWorkerPool() stream.IWorkerPool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerPool")
	ret0, _ := ret[0].(stream.IWorkerPool)
	return ret0
}

// GetWorkerPool indicates an expected call of GetWorkerPool.
func (mr *MockIWorkerContainerMockRecorder) GetWorkerPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerPool", reflect.TypeOf((*MockIWorkerContainer)(nil).GetWorkerPool))
}
