// Code generated by MockGen. DO NOT EDIT.
// Source: pool.go
//
// Generated by this command:
//
//	mockgen -source=pool.go -destination=../../mocks/stream/pool.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	bufio "bufio"
	reflect "reflect"

	stream "github.com/amirdaaee/TGMon/internal/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockIWorkerPool is a mock of IWorkerPool interface.
type MockIWorkerPool struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkerPoolMockRecorder
	isgomock struct{}
}

// MockIWorkerPoolMockRecorder is the mock recorder for MockIWorkerPool.
type MockIWorkerPoolMockRecorder struct {
	mock *MockIWorkerPool
}

// NewMockIWorkerPool creates a new mock instance.
func NewMockIWorkerPool(ctrl *gomock.Controller) *MockIWorkerPool {
	mock := &MockIWorkerPool{ctrl: ctrl}
	mock.recorder = &MockIWorkerPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkerPool) EXPECT() *MockIWorkerPoolMockRecorder {
	return m.recorder
}

// GetNextWorker mocks base method.
func (m *MockIWorkerPool) GetNextWorker() stream.IWorker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextWorker")
	ret0, _ := ret[0].(stream.IWorker)
	return ret0
}

// GetNextWorker indicates an expected call of GetNextWorker.
func (mr *MockIWorkerPoolMockRecorder) GetNextWorker() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextWorker", reflect.TypeOf((*MockIWorkerPool)(nil).GetNextWorker))
}

// MockIStreamer is a mock of IStreamer interface.
type MockIStreamer struct {
	ctrl     *gomock.Controller
	recorder *MockIStreamerMockRecorder
	isgomock struct{}
}

// MockIStreamerMockRecorder is the mock recorder for MockIStreamer.
type MockIStreamerMockRecorder struct {
	mock *MockIStreamer
}

// NewMockIStreamer creates a new mock instance.
func NewMockIStreamer(ctrl *gomock.Controller) *MockIStreamer {
	mock := &MockIStreamer{ctrl: ctrl}
	mock.recorder = &MockIStreamerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStreamer) EXPECT() *MockIStreamerMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockIStreamer) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockIStreamerMockRecorder) Read(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockIStreamer)(nil).Read), p)
}

// ReadBuffered mocks base method.
func (m *MockIStreamer) ReadBuffered() *bufio.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBuffered")
	ret0, _ := ret[0].(*bufio.Reader)
	return ret0
}

// ReadBuffered indicates an expected call of ReadBuffered.
func (mr *MockIStreamerMockRecorder) ReadBuffered() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBuffered", reflect.TypeOf((*MockIStreamer)(nil).ReadBuffered))
}
