// Code generated by kessoku. DO NOT EDIT.

package app

import (
	"github.com/amirdaaee/TGMon/internal/bot"
	"github.com/amirdaaee/TGMon/internal/config"
	"github.com/mazrean/kessoku"
)

func InitializeBot(configType *config.ConfigType) (*bot.Bot, error) {
	sessionConfig := kessoku.Provide(NewTgSessionConfig).Fn()(configType)
	var err error
	idbContainer, err := kessoku.Provide(NewDbContainer).Fn()(configType)
	if err != nil {
		var zero *bot.Bot
		return zero, err
	}
	iclient := kessoku.Provide(NewTgClient).Fn()(configType, sessionConfig)
	var err0 error
	iworkerPool, err0 := kessoku.Provide(NewTgWorkerPool).Fn()(configType, sessionConfig)
	if err0 != nil {
		var zero *bot.Bot
		return zero, err0
	}
	ifacade := kessoku.Provide(NewMediaFacade).Fn()(idbContainer, iworkerPool)
	var err1 error
	bot0, err1 := kessoku.Provide(NewBot).Fn()(iclient, ifacade, iworkerPool)
	if err1 != nil {
		var zero *bot.Bot
		return zero, err1
	}
	return bot0, nil
}
