// Code generated by kessoku. DO NOT EDIT.

package app

import (
	"github.com/amirdaaee/TGMon/internal/config"
	"github.com/hanwen/go-fuse/v2/fuse"
	"github.com/mazrean/kessoku"
)

func InitializeFuzeServer(configType *config.ConfigType) (*fuse.Server, error) {
	var err error
	idbContainer, err := kessoku.Provide(NewDbContainer).Fn()(configType)
	if err != nil {
		var zero *fuse.Server
		return zero, err
	}
	sessionConfig := kessoku.Provide(NewTgSessionConfig).Fn()(configType)
	var err0 error
	iworkerPool, err0 := kessoku.Provide(NewTgWorkerPool).Fn()(configType, sessionConfig)
	if err0 != nil {
		var zero *fuse.Server
		return zero, err0
	}
	var err1 error
	server, err1 := kessoku.Provide(NewFuzeServer).Fn()(configType, idbContainer, iworkerPool)
	if err1 != nil {
		var zero *fuse.Server
		return zero, err1
	}
	return server, nil
}
