// Code generated by kessoku. DO NOT EDIT.

package app

import (
	"net/http"

	"github.com/amirdaaee/TGMon/internal/config"
	"github.com/mazrean/kessoku"
)

func InitializeWebServer(configType *config.ConfigType) (*http.Server, error) {
	var err error
	idbContainer, err := kessoku.Provide(NewDbContainer).Fn()(configType)
	if err != nil {
		var zero *http.Server
		return zero, err
	}
	stashQlClient := kessoku.Provide(NewStashQlClient).Fn()(configType)
	sessionConfig := kessoku.Provide(NewTgSessionConfig).Fn()(configType)
	ifacade := kessoku.Provide(NewJobReqFacade).Fn()(idbContainer)
	ifacade0 := kessoku.Provide(NewJobResFacade).Fn()(idbContainer)
	var err0 error
	iworkerPool, err0 := kessoku.Provide(NewTgWorkerPool).Fn()(configType, sessionConfig)
	if err0 != nil {
		var zero *http.Server
		return zero, err0
	}
	ifacade1 := kessoku.Provide(NewMediaFacade).Fn()(idbContainer, iworkerPool)
	handlerContainer := kessoku.Provide(NewWebHandler).Fn()(configType, idbContainer, ifacade1, ifacade, ifacade0, iworkerPool, stashQlClient)
	engine := kessoku.Provide(NewGinEngine).Fn()(configType, handlerContainer)
	server := kessoku.Provide(NewWebServer).Fn()(configType, engine, handlerContainer)
	return server, nil
}
