// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"net/http"

	"github.com/amirdaaee/TGMon/internal/bot"
	"github.com/amirdaaee/TGMon/internal/config"
	"github.com/hanwen/go-fuse/v2/fuse"
)

// Injectors from bot.go:

func InitializeBot(cfg *config.ConfigType) (*bot.Bot, error) {
	sessionConfig := NewTgSessionConfig(cfg)
	iClient := NewTgClient(cfg, sessionConfig)
	iDbContainer, err := NewDbContainer(cfg)
	if err != nil {
		return nil, err
	}
	iWorkerPool, err := NewTgWorkerPool(cfg, sessionConfig)
	if err != nil {
		return nil, err
	}
	iFacade := NewJobReqFacade(iDbContainer)
	typesIFacade := NewMediaFacade(iDbContainer, iWorkerPool, iFacade)
	botBot, err := NewBot(iClient, typesIFacade, iWorkerPool)
	if err != nil {
		return nil, err
	}
	return botBot, nil
}

// Injectors from server.go:

func InitializeServer(cfg *config.ConfigType) (*ServerModules, error) {
	iDbContainer, err := NewDbContainer(cfg)
	if err != nil {
		return nil, err
	}
	sessionConfig := NewTgSessionConfig(cfg)
	iWorkerPool, err := NewTgWorkerPool(cfg, sessionConfig)
	if err != nil {
		return nil, err
	}
	iFacade := NewJobReqFacade(iDbContainer)
	typesIFacade := NewMediaFacade(iDbContainer, iWorkerPool, iFacade)
	iFacade2 := NewJobResFacade(iDbContainer, iFacade)
	stashQlClient := NewStashQlClient(cfg)
	v := NewWebHandler(cfg, iDbContainer, typesIFacade, iFacade, iFacade2, iWorkerPool, stashQlClient)
	engine := NewGinEngine(cfg, v)
	server := NewWebServer(cfg, engine, v)
	fuseServer, err := NewFuzeServer(cfg, typesIFacade, iWorkerPool)
	if err != nil {
		return nil, err
	}
	serverModules := &ServerModules{
		WebServer:  server,
		FuzeServer: fuseServer,
	}
	return serverModules, nil
}

// server.go:

type ServerModules struct {
	WebServer  *http.Server
	FuzeServer *fuse.Server
}
