// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=../../mocks/worker/cache.go -package=mocks_worker
//

// Package mocks_worker is a generated GoMock package.
package mocks_worker

import (
	context "context"
	reflect "reflect"

	tg "github.com/gotd/td/tg"
	gomock "go.uber.org/mock/gomock"
)

// MockITGDocCache is a mock of ITGDocCache interface.
type MockITGDocCache struct {
	ctrl     *gomock.Controller
	recorder *MockITGDocCacheMockRecorder
	isgomock struct{}
}

// MockITGDocCacheMockRecorder is the mock recorder for MockITGDocCache.
type MockITGDocCacheMockRecorder struct {
	mock *MockITGDocCache
}

// NewMockITGDocCache creates a new mock instance.
func NewMockITGDocCache(ctrl *gomock.Controller) *MockITGDocCache {
	mock := &MockITGDocCache{ctrl: ctrl}
	mock.recorder = &MockITGDocCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITGDocCache) EXPECT() *MockITGDocCacheMockRecorder {
	return m.recorder
}

// GetOrSet mocks base method.
func (m *MockITGDocCache) GetOrSet(ctx context.Context, WorkerID int64, messageID int, fn func() (*tg.Document, error)) (*tg.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrSet", ctx, WorkerID, messageID, fn)
	ret0, _ := ret[0].(*tg.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrSet indicates an expected call of GetOrSet.
func (mr *MockITGDocCacheMockRecorder) GetOrSet(ctx, WorkerID, messageID, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrSet", reflect.TypeOf((*MockITGDocCache)(nil).GetOrSet), ctx, WorkerID, messageID, fn)
}
