// Code generated by MockGen. DO NOT EDIT.
// Source: internal/facade/types/crd.go
//
// Generated by this command:
//
//	mockgen -source=internal/facade/types/crd.go -destination=mocks/facade/types/crd.go -package=mocks_facade_types
//

// Package mocks_facade_types is a generated GoMock package.
package mocks_facade_types

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICrud is a mock of ICrud interface.
type MockICrud[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockICrudMockRecorder[T]
	isgomock struct{}
}

// MockICrudMockRecorder is the mock recorder for MockICrud.
type MockICrudMockRecorder[T any] struct {
	mock *MockICrud[T]
}

// NewMockICrud creates a new mock instance.
func NewMockICrud[T any](ctrl *gomock.Controller) *MockICrud[T] {
	mock := &MockICrud[T]{ctrl: ctrl}
	mock.recorder = &MockICrudMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICrud[T]) EXPECT() *MockICrudMockRecorder[T] {
	return m.recorder
}

// PostCreate mocks base method.
func (m *MockICrud[T]) PostCreate(ctx context.Context, doc *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostCreate", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostCreate indicates an expected call of PostCreate.
func (mr *MockICrudMockRecorder[T]) PostCreate(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostCreate", reflect.TypeOf((*MockICrud[T])(nil).PostCreate), ctx, doc)
}

// PostDelete mocks base method.
func (m *MockICrud[T]) PostDelete(ctx context.Context, doc *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostDelete", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostDelete indicates an expected call of PostDelete.
func (mr *MockICrudMockRecorder[T]) PostDelete(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostDelete", reflect.TypeOf((*MockICrud[T])(nil).PostDelete), ctx, doc)
}

// PreCreate mocks base method.
func (m *MockICrud[T]) PreCreate(ctx context.Context, doc *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreCreate", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreCreate indicates an expected call of PreCreate.
func (mr *MockICrudMockRecorder[T]) PreCreate(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreCreate", reflect.TypeOf((*MockICrud[T])(nil).PreCreate), ctx, doc)
}

// PreDelete mocks base method.
func (m *MockICrud[T]) PreDelete(ctx context.Context, doc *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreDelete", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreDelete indicates an expected call of PreDelete.
func (mr *MockICrudMockRecorder[T]) PreDelete(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreDelete", reflect.TypeOf((*MockICrud[T])(nil).PreDelete), ctx, doc)
}
