// Code generated by MockGen. DO NOT EDIT.
// Source: facade.go
//
// Generated by this command:
//
//	mockgen -source=facade.go -destination=../../../mocks/facade/types/facade.go -package=mocks_facade_types
//

// Package mocks_facade_types is a generated GoMock package.
package mocks_facade_types

import (
	context "context"
	reflect "reflect"

	types "github.com/amirdaaee/TGMon/internal/facade/types"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockIFacade is a mock of IFacade interface.
type MockIFacade[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockIFacadeMockRecorder[T]
	isgomock struct{}
}

// MockIFacadeMockRecorder is the mock recorder for MockIFacade.
type MockIFacadeMockRecorder[T any] struct {
	mock *MockIFacade[T]
}

// NewMockIFacade creates a new mock instance.
func NewMockIFacade[T any](ctrl *gomock.Controller) *MockIFacade[T] {
	mock := &MockIFacade[T]{ctrl: ctrl}
	mock.recorder = &MockIFacadeMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFacade[T]) EXPECT() *MockIFacadeMockRecorder[T] {
	return m.recorder
}

// CreateOne mocks base method.
func (m *MockIFacade[T]) CreateOne(ctx context.Context, doc *T) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOne", ctx, doc)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOne indicates an expected call of CreateOne.
func (mr *MockIFacadeMockRecorder[T]) CreateOne(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOne", reflect.TypeOf((*MockIFacade[T])(nil).CreateOne), ctx, doc)
}

// DeleteByID mocks base method.
func (m *MockIFacade[T]) DeleteByID(ctx context.Context, id bson.ObjectID) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIFacadeMockRecorder[T]) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIFacade[T])(nil).DeleteByID), ctx, id)
}

// FindByID mocks base method.
func (m *MockIFacade[T]) FindByID(ctx context.Context, id bson.ObjectID) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIFacadeMockRecorder[T]) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIFacade[T])(nil).FindByID), ctx, id)
}

// GetCRD mocks base method.
func (m *MockIFacade[T]) GetCRD() types.ICrud[T] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCRD")
	ret0, _ := ret[0].(types.ICrud[T])
	return ret0
}

// GetCRD indicates an expected call of GetCRD.
func (mr *MockIFacadeMockRecorder[T]) GetCRD() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCRD", reflect.TypeOf((*MockIFacade[T])(nil).GetCRD))
}
