// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/fuse.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/fuse.go -destination=mocks/repository/fuse.go -package=mocks_repository
//

// Package mocks_repository is a generated GoMock package.
package mocks_repository

import (
	context "context"
	reflect "reflect"

	types "github.com/amirdaaee/TGMon/internal/types"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockFuseStateRepository is a mock of FuseStateRepository interface.
type MockFuseStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFuseStateRepositoryMockRecorder
	isgomock struct{}
}

// MockFuseStateRepositoryMockRecorder is the mock recorder for MockFuseStateRepository.
type MockFuseStateRepositoryMockRecorder struct {
	mock *MockFuseStateRepository
}

// NewMockFuseStateRepository creates a new mock instance.
func NewMockFuseStateRepository(ctrl *gomock.Controller) *MockFuseStateRepository {
	mock := &MockFuseStateRepository{ctrl: ctrl}
	mock.recorder = &MockFuseStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFuseStateRepository) EXPECT() *MockFuseStateRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockFuseStateRepository) DeleteByID(ctx context.Context, id bson.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockFuseStateRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockFuseStateRepository)(nil).DeleteByID), ctx, id)
}

// Insert mocks base method.
func (m *MockFuseStateRepository) Insert(ctx context.Context, doc *types.FuseStateDoc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockFuseStateRepositoryMockRecorder) Insert(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockFuseStateRepository)(nil).Insert), ctx, doc)
}

// List mocks base method.
func (m *MockFuseStateRepository) List(ctx context.Context) ([]*types.FuseStateDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*types.FuseStateDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFuseStateRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFuseStateRepository)(nil).List), ctx)
}

// SetRename mocks base method.
func (m *MockFuseStateRepository) SetRename(ctx context.Context, id bson.ObjectID, rename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRename", ctx, id, rename)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRename indicates an expected call of SetRename.
func (mr *MockFuseStateRepositoryMockRecorder) SetRename(ctx, id, rename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRename", reflect.TypeOf((*MockFuseStateRepository)(nil).SetRename), ctx, id, rename)
}
