// Code generated by MockGen. DO NOT EDIT.
// Source: job.go
//
// Generated by this command:
//
//	mockgen -source=job.go -destination=../../mocks/repository/job.go -package=mocks_repository
//

// Package mocks_repository is a generated GoMock package.
package mocks_repository

import (
	context "context"
	reflect "reflect"

	types "github.com/amirdaaee/TGMon/internal/types"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockJobReqRepository is a mock of JobReqRepository interface.
type MockJobReqRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobReqRepositoryMockRecorder
	isgomock struct{}
}

// MockJobReqRepositoryMockRecorder is the mock recorder for MockJobReqRepository.
type MockJobReqRepositoryMockRecorder struct {
	mock *MockJobReqRepository
}

// NewMockJobReqRepository creates a new mock instance.
func NewMockJobReqRepository(ctrl *gomock.Controller) *MockJobReqRepository {
	mock := &MockJobReqRepository{ctrl: ctrl}
	mock.recorder = &MockJobReqRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobReqRepository) EXPECT() *MockJobReqRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockJobReqRepository) DeleteByID(ctx context.Context, id bson.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockJobReqRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockJobReqRepository)(nil).DeleteByID), ctx, id)
}

// DeleteByMediaID mocks base method.
func (m *MockJobReqRepository) DeleteByMediaID(ctx context.Context, mediaID bson.ObjectID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByMediaID", ctx, mediaID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByMediaID indicates an expected call of DeleteByMediaID.
func (mr *MockJobReqRepositoryMockRecorder) DeleteByMediaID(ctx, mediaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMediaID", reflect.TypeOf((*MockJobReqRepository)(nil).DeleteByMediaID), ctx, mediaID)
}

// FindByID mocks base method.
func (m *MockJobReqRepository) FindByID(ctx context.Context, id bson.ObjectID) (*types.JobReqDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*types.JobReqDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockJobReqRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockJobReqRepository)(nil).FindByID), ctx, id)
}

// Insert mocks base method.
func (m *MockJobReqRepository) Insert(ctx context.Context, doc *types.JobReqDoc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockJobReqRepositoryMockRecorder) Insert(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockJobReqRepository)(nil).Insert), ctx, doc)
}

// List mocks base method.
func (m *MockJobReqRepository) List(ctx context.Context) ([]*types.JobReqDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*types.JobReqDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockJobReqRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockJobReqRepository)(nil).List), ctx)
}

// MockJobResRepository is a mock of JobResRepository interface.
type MockJobResRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobResRepositoryMockRecorder
	isgomock struct{}
}

// MockJobResRepositoryMockRecorder is the mock recorder for MockJobResRepository.
type MockJobResRepositoryMockRecorder struct {
	mock *MockJobResRepository
}

// NewMockJobResRepository creates a new mock instance.
func NewMockJobResRepository(ctrl *gomock.Controller) *MockJobResRepository {
	mock := &MockJobResRepository{ctrl: ctrl}
	mock.recorder = &MockJobResRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobResRepository) EXPECT() *MockJobResRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockJobResRepository) DeleteByID(ctx context.Context, id bson.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockJobResRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockJobResRepository)(nil).DeleteByID), ctx, id)
}

// FindByID mocks base method.
func (m *MockJobResRepository) FindByID(ctx context.Context, id bson.ObjectID) (*types.JobResDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*types.JobResDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockJobResRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockJobResRepository)(nil).FindByID), ctx, id)
}

// Insert mocks base method.
func (m *MockJobResRepository) Insert(ctx context.Context, doc *types.JobResDoc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockJobResRepositoryMockRecorder) Insert(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockJobResRepository)(nil).Insert), ctx, doc)
}
