// Code generated by MockGen. DO NOT EDIT.
// Source: mediaMeta.go
//
// Generated by this command:
//
//	mockgen -source=mediaMeta.go -destination=../../mocks/repository/mediaMeta.go -package=mocks_repository
//

// Package mocks_repository is a generated GoMock package.
package mocks_repository

import (
	context "context"
	reflect "reflect"

	types "github.com/amirdaaee/TGMon/internal/types"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockMediaExtendedMetaRepository is a mock of MediaExtendedMetaRepository interface.
type MockMediaExtendedMetaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMediaExtendedMetaRepositoryMockRecorder
	isgomock struct{}
}

// MockMediaExtendedMetaRepositoryMockRecorder is the mock recorder for MockMediaExtendedMetaRepository.
type MockMediaExtendedMetaRepositoryMockRecorder struct {
	mock *MockMediaExtendedMetaRepository
}

// NewMockMediaExtendedMetaRepository creates a new mock instance.
func NewMockMediaExtendedMetaRepository(ctrl *gomock.Controller) *MockMediaExtendedMetaRepository {
	mock := &MockMediaExtendedMetaRepository{ctrl: ctrl}
	mock.recorder = &MockMediaExtendedMetaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaExtendedMetaRepository) EXPECT() *MockMediaExtendedMetaRepositoryMockRecorder {
	return m.recorder
}

// DeleteByMediaFileID mocks base method.
func (m *MockMediaExtendedMetaRepository) DeleteByMediaFileID(ctx context.Context, mediaFileID bson.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByMediaFileID", ctx, mediaFileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByMediaFileID indicates an expected call of DeleteByMediaFileID.
func (mr *MockMediaExtendedMetaRepositoryMockRecorder) DeleteByMediaFileID(ctx, mediaFileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMediaFileID", reflect.TypeOf((*MockMediaExtendedMetaRepository)(nil).DeleteByMediaFileID), ctx, mediaFileID)
}

// GetOrCreateByMediaFileID mocks base method.
func (m *MockMediaExtendedMetaRepository) GetOrCreateByMediaFileID(ctx context.Context, mediaFileID bson.ObjectID) (*types.MediaExtendedMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateByMediaFileID", ctx, mediaFileID)
	ret0, _ := ret[0].(*types.MediaExtendedMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateByMediaFileID indicates an expected call of GetOrCreateByMediaFileID.
func (mr *MockMediaExtendedMetaRepositoryMockRecorder) GetOrCreateByMediaFileID(ctx, mediaFileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateByMediaFileID", reflect.TypeOf((*MockMediaExtendedMetaRepository)(nil).GetOrCreateByMediaFileID), ctx, mediaFileID)
}

// PatchByMediaFileID mocks base method.
func (m *MockMediaExtendedMetaRepository) PatchByMediaFileID(ctx context.Context, mediaFileID bson.ObjectID, patch types.MediaExtendedMetaPatch) (*types.MediaExtendedMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchByMediaFileID", ctx, mediaFileID, patch)
	ret0, _ := ret[0].(*types.MediaExtendedMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchByMediaFileID indicates an expected call of PatchByMediaFileID.
func (mr *MockMediaExtendedMetaRepositoryMockRecorder) PatchByMediaFileID(ctx, mediaFileID, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchByMediaFileID", reflect.TypeOf((*MockMediaExtendedMetaRepository)(nil).PatchByMediaFileID), ctx, mediaFileID, patch)
}

// ReplaceByMediaFileID mocks base method.
func (m *MockMediaExtendedMetaRepository) ReplaceByMediaFileID(ctx context.Context, mediaFileID bson.ObjectID, doc *types.MediaExtendedMeta) (*types.MediaExtendedMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceByMediaFileID", ctx, mediaFileID, doc)
	ret0, _ := ret[0].(*types.MediaExtendedMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceByMediaFileID indicates an expected call of ReplaceByMediaFileID.
func (mr *MockMediaExtendedMetaRepositoryMockRecorder) ReplaceByMediaFileID(ctx, mediaFileID, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceByMediaFileID", reflect.TypeOf((*MockMediaExtendedMetaRepository)(nil).ReplaceByMediaFileID), ctx, mediaFileID, doc)
}
