// Code generated by MockGen. DO NOT EDIT.
// Source: media.go
//
// Generated by this command:
//
//	mockgen -source=media.go -destination=../../mocks/repository/media.go -package=mocks_repository
//

// Package mocks_repository is a generated GoMock package.
package mocks_repository

import (
	context "context"
	reflect "reflect"

	types "github.com/amirdaaee/TGMon/internal/types"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockMediaFileRepository is a mock of MediaFileRepository interface.
type MockMediaFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMediaFileRepositoryMockRecorder
	isgomock struct{}
}

// MockMediaFileRepositoryMockRecorder is the mock recorder for MockMediaFileRepository.
type MockMediaFileRepositoryMockRecorder struct {
	mock *MockMediaFileRepository
}

// NewMockMediaFileRepository creates a new mock instance.
func NewMockMediaFileRepository(ctrl *gomock.Controller) *MockMediaFileRepository {
	mock := &MockMediaFileRepository{ctrl: ctrl}
	mock.recorder = &MockMediaFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaFileRepository) EXPECT() *MockMediaFileRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockMediaFileRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockMediaFileRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockMediaFileRepository)(nil).Count), ctx)
}

// CountByFileID mocks base method.
func (m *MockMediaFileRepository) CountByFileID(ctx context.Context, fileID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByFileID", ctx, fileID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByFileID indicates an expected call of CountByFileID.
func (mr *MockMediaFileRepositoryMockRecorder) CountByFileID(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByFileID", reflect.TypeOf((*MockMediaFileRepository)(nil).CountByFileID), ctx, fileID)
}

// DeleteByID mocks base method.
func (m *MockMediaFileRepository) DeleteByID(ctx context.Context, id bson.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockMediaFileRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockMediaFileRepository)(nil).DeleteByID), ctx, id)
}

// FindByID mocks base method.
func (m *MockMediaFileRepository) FindByID(ctx context.Context, id bson.ObjectID) (*types.MediaFileDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*types.MediaFileDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMediaFileRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMediaFileRepository)(nil).FindByID), ctx, id)
}

// FindByUName mocks base method.
func (m *MockMediaFileRepository) FindByUName(ctx context.Context, uname string) (*types.MediaFileDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUName", ctx, uname)
	ret0, _ := ret[0].(*types.MediaFileDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUName indicates an expected call of FindByUName.
func (mr *MockMediaFileRepositoryMockRecorder) FindByUName(ctx, uname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUName", reflect.TypeOf((*MockMediaFileRepository)(nil).FindByUName), ctx, uname)
}

// FindNeighbors mocks base method.
func (m *MockMediaFileRepository) FindNeighbors(ctx context.Context, doc *types.MediaFileDoc) (*bson.ObjectID, *bson.ObjectID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNeighbors", ctx, doc)
	ret0, _ := ret[0].(*bson.ObjectID)
	ret1, _ := ret[1].(*bson.ObjectID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindNeighbors indicates an expected call of FindNeighbors.
func (mr *MockMediaFileRepositoryMockRecorder) FindNeighbors(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNeighbors", reflect.TypeOf((*MockMediaFileRepository)(nil).FindNeighbors), ctx, doc)
}

// FindRandom mocks base method.
func (m *MockMediaFileRepository) FindRandom(ctx context.Context) (*types.MediaFileDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRandom", ctx)
	ret0, _ := ret[0].(*types.MediaFileDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRandom indicates an expected call of FindRandom.
func (mr *MockMediaFileRepositoryMockRecorder) FindRandom(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRandom", reflect.TypeOf((*MockMediaFileRepository)(nil).FindRandom), ctx)
}

// Insert mocks base method.
func (m *MockMediaFileRepository) Insert(ctx context.Context, doc *types.MediaFileDoc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockMediaFileRepositoryMockRecorder) Insert(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMediaFileRepository)(nil).Insert), ctx, doc)
}

// ListByID mocks base method.
func (m *MockMediaFileRepository) ListByID(ctx context.Context) ([]*types.MediaFileDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByID", ctx)
	ret0, _ := ret[0].([]*types.MediaFileDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByID indicates an expected call of ListByID.
func (mr *MockMediaFileRepositoryMockRecorder) ListByID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByID", reflect.TypeOf((*MockMediaFileRepository)(nil).ListByID), ctx)
}

// ListPage mocks base method.
func (m *MockMediaFileRepository) ListPage(ctx context.Context, page, pageSize int) ([]*types.MediaFileDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPage", ctx, page, pageSize)
	ret0, _ := ret[0].([]*types.MediaFileDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPage indicates an expected call of ListPage.
func (mr *MockMediaFileRepositoryMockRecorder) ListPage(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPage", reflect.TypeOf((*MockMediaFileRepository)(nil).ListPage), ctx, page, pageSize)
}

// SetHasHash mocks base method.
func (m *MockMediaFileRepository) SetHasHash(ctx context.Context, id bson.ObjectID, has bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHasHash", ctx, id, has)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHasHash indicates an expected call of SetHasHash.
func (mr *MockMediaFileRepositoryMockRecorder) SetHasHash(ctx, id, has any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasHash", reflect.TypeOf((*MockMediaFileRepository)(nil).SetHasHash), ctx, id, has)
}

// SetSpriteAndVtt mocks base method.
func (m *MockMediaFileRepository) SetSpriteAndVtt(ctx context.Context, id bson.ObjectID, sprite, vtt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSpriteAndVtt", ctx, id, sprite, vtt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSpriteAndVtt indicates an expected call of SetSpriteAndVtt.
func (mr *MockMediaFileRepositoryMockRecorder) SetSpriteAndVtt(ctx, id, sprite, vtt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSpriteAndVtt", reflect.TypeOf((*MockMediaFileRepository)(nil).SetSpriteAndVtt), ctx, id, sprite, vtt)
}

// SetSrt mocks base method.
func (m *MockMediaFileRepository) SetSrt(ctx context.Context, id bson.ObjectID, srt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSrt", ctx, id, srt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSrt indicates an expected call of SetSrt.
func (mr *MockMediaFileRepositoryMockRecorder) SetSrt(ctx, id, srt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSrt", reflect.TypeOf((*MockMediaFileRepository)(nil).SetSrt), ctx, id, srt)
}

// SetThumbnail mocks base method.
func (m *MockMediaFileRepository) SetThumbnail(ctx context.Context, id bson.ObjectID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetThumbnail", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetThumbnail indicates an expected call of SetThumbnail.
func (mr *MockMediaFileRepositoryMockRecorder) SetThumbnail(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetThumbnail", reflect.TypeOf((*MockMediaFileRepository)(nil).SetThumbnail), ctx, id, name)
}

// SetUName mocks base method.
func (m *MockMediaFileRepository) SetUName(ctx context.Context, id bson.ObjectID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUName", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUName indicates an expected call of SetUName.
func (mr *MockMediaFileRepositoryMockRecorder) SetUName(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUName", reflect.TypeOf((*MockMediaFileRepository)(nil).SetUName), ctx, id, name)
}
