// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/store.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/store.go -destination=mocks/repository/store.go -package=mocks_repository
//

// Package mocks_repository is a generated GoMock package.
package mocks_repository

import (
	context "context"
	reflect "reflect"

	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder[T]
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder[T any] struct {
	mock *MockStore[T]
}

// NewMockStore creates a new mock instance.
func NewMockStore[T any](ctrl *gomock.Controller) *MockStore[T] {
	mock := &MockStore[T]{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore[T]) EXPECT() *MockStoreMockRecorder[T] {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockStore[T]) DeleteByID(ctx context.Context, id bson.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockStoreMockRecorder[T]) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockStore[T])(nil).DeleteByID), ctx, id)
}

// FindByID mocks base method.
func (m *MockStore[T]) FindByID(ctx context.Context, id bson.ObjectID) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockStoreMockRecorder[T]) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStore[T])(nil).FindByID), ctx, id)
}

// Insert mocks base method.
func (m *MockStore[T]) Insert(ctx context.Context, doc *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockStoreMockRecorder[T]) Insert(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockStore[T])(nil).Insert), ctx, doc)
}
