// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go
//
// Generated by this command:
//
//	mockgen -source=worker.go -destination=../../mocks/repository/worker.go -package=mocks_repository
//

// Package mocks_repository is a generated GoMock package.
package mocks_repository

import (
	context "context"
	reflect "reflect"

	tg "github.com/gotd/td/tg"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkerMediaRepository is a mock of WorkerMediaRepository interface.
type MockWorkerMediaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMediaRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkerMediaRepositoryMockRecorder is the mock recorder for MockWorkerMediaRepository.
type MockWorkerMediaRepositoryMockRecorder struct {
	mock *MockWorkerMediaRepository
}

// NewMockWorkerMediaRepository creates a new mock instance.
func NewMockWorkerMediaRepository(ctrl *gomock.Controller) *MockWorkerMediaRepository {
	mock := &MockWorkerMediaRepository{ctrl: ctrl}
	mock.recorder = &MockWorkerMediaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerMediaRepository) EXPECT() *MockWorkerMediaRepositoryMockRecorder {
	return m.recorder
}

// GetTelegramDoc mocks base method.
func (m *MockWorkerMediaRepository) GetTelegramDoc(ctx context.Context, WorkerID int64, messageID int) (*tg.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelegramDoc", ctx, WorkerID, messageID)
	ret0, _ := ret[0].(*tg.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTelegramDoc indicates an expected call of GetTelegramDoc.
func (mr *MockWorkerMediaRepositoryMockRecorder) GetTelegramDoc(ctx, WorkerID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelegramDoc", reflect.TypeOf((*MockWorkerMediaRepository)(nil).GetTelegramDoc), ctx, WorkerID, messageID)
}

// SetTelegramDoc mocks base method.
func (m *MockWorkerMediaRepository) SetTelegramDoc(ctx context.Context, WorkerID int64, messageID int, telegramDoc *tg.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTelegramDoc", ctx, WorkerID, messageID, telegramDoc)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTelegramDoc indicates an expected call of SetTelegramDoc.
func (mr *MockWorkerMediaRepositoryMockRecorder) SetTelegramDoc(ctx, WorkerID, messageID, telegramDoc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTelegramDoc", reflect.TypeOf((*MockWorkerMediaRepository)(nil).SetTelegramDoc), ctx, WorkerID, messageID, telegramDoc)
}
