// Code generated by MockGen. DO NOT EDIT.
// Source: container.go
//
// Generated by this command:
//
//	mockgen -source=container.go -destination=../../../mocks/db/minio/container.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	minio "github.com/amirdaaee/TGMon/internal/db/minio"
	gomock "go.uber.org/mock/gomock"
)

// MockIMinioContainer is a mock of IMinioContainer interface.
type MockIMinioContainer struct {
	ctrl     *gomock.Controller
	recorder *MockIMinioContainerMockRecorder
	isgomock struct{}
}

// MockIMinioContainerMockRecorder is the mock recorder for MockIMinioContainer.
type MockIMinioContainerMockRecorder struct {
	mock *MockIMinioContainer
}

// NewMockIMinioContainer creates a new mock instance.
func NewMockIMinioContainer(ctrl *gomock.Controller) *MockIMinioContainer {
	mock := &MockIMinioContainer{ctrl: ctrl}
	mock.recorder = &MockIMinioContainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMinioContainer) EXPECT() *MockIMinioContainerMockRecorder {
	return m.recorder
}

// GetMinioClient mocks base method.
func (m *MockIMinioContainer) GetMinioClient() minio.IMinioClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinioClient")
	ret0, _ := ret[0].(minio.IMinioClient)
	return ret0
}

// GetMinioClient indicates an expected call of GetMinioClient.
func (mr *MockIMinioContainerMockRecorder) GetMinioClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinioClient", reflect.TypeOf((*MockIMinioContainer)(nil).GetMinioClient))
}
